name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
        
    - name: Restore dependencies
      run: |
        dotnet restore src/TrocaDeFigurinhas/TrocaDeFigurinhas.csproj
        dotnet restore src/TrocaDeFigurinhas.Tests.Unit/TrocaDeFigurinhas.Tests.Unit.csproj
      
    - name: Build
      run: |
        dotnet build src/TrocaDeFigurinhas/TrocaDeFigurinhas.csproj --no-restore
        dotnet build src/TrocaDeFigurinhas.Tests.Unit/TrocaDeFigurinhas.Tests.Unit.csproj --no-restore
      env:
        DB_CONNECTION_STRING: "Host=localhost;Database=test"

    - name: Run Unit Tests
      run: dotnet test src/TrocaDeFigurinhas.Tests.Unit/TrocaDeFigurinhas.Tests.Unit.csproj --no-build --verbosity normal
      env:
        DB_CONNECTION_STRING: "Host=localhost;Database=test"
